entries/routes.py
import secrets
import string
from datetime import datetime
from flask import (Blueprint, render_template, url_for, flash, redirect,
                    request, abort, session)
from flask_login import current_user, login_required
from sqlalchemy.exc import IntegrityError
from app import db, bcrypt
from app.models import Entry
from app.entries.utils import (encrypt, decrypt, check_generator,
                                check_password, to_csv, to_json)
from app.entries.forms import EntryForm, GeneratorForm, ExportForm


entries = Blueprint("entries", __name__)


@entries.route("/add", methods=["GET", "POST"])
@login_required
def add():
    form = EntryForm()
    if form.validate_on_submit():
        entry = Entry(
                    name=form.name.data,
                    username=form.username.data,
                    password=encrypt((form.password.data).encode("utf-8")),
                    url=form.url.data,
                    notes=form.notes.data,
                    owner=current_user,
                    )
        db.session.add(entry)
        try:
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
            flash("Entry already exists.", "danger")
            return redirect(url_for("entries.add"))
        flash("Entry has been successfully created.", "success")
        return redirect(url_for("main.index"))
    return render_template("add.html", title="Add Entry", form=form, text="Add Entry")


@entries.route("/edit/<int:entry_id>", methods=["GET", "POST"])
@login_required
def edit(entry_id):
    entry = Entry.query.get_or_404(entry_id)
    if entry.owner != current_user:
        abort(403)
    form = EntryForm()
    if request.method == "GET":
        form.name.data = entry.name
        form.username.data = entry.username
        form.password.data = decrypt(entry.password).decode("utf-8")
        form.url.data = entry.url
        form.notes.data = entry.notes
    elif form.validate_on_submit():
        entry.name = form.name.data
        entry.last_modified = datetime.utcnow()
        entry.username = form.username.data
        entry.password = encrypt((form.password.data).encode("utf-8"))
        entry.url = form.url.data
        entry.notes = form.notes.data
        try:
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
            flash("Entry already exists.", "danger")
            return redirect(url_for("entries.edit", entry_id=entry.id))
        flash("Entry has been successfully updated.", "success")
        return redirect(url_for("main.index"))
    return render_template("add.html", title="Edit Entry", form=form, text="Edit Entry")


@entries.route("/delete/<int:entry_id>", methods=["GET", "POST"])
@login_required
def delete(entry_id):
    entry = Entry.query.get_or_404(entry_id)
    if entry.owner != current_user:
        abort(403)
    db.session.delete(entry)
    db.session.commit()
    flash("Entry has been successfully deleted.", "success")
    return redirect(url_for("main.index"))


@entries.route("/tools/generator", methods=["GET", "POST"])
@login_required
def generator():
    form = GeneratorForm()
    if request.method == "GET":
        form.length.data = session.get("length", "12")
        form.uppercase.data = session.get("uppercase", "y")
        form.lowercase.data = session.get("lowercase", "y")
        form.digits.data = session.get("digits", "y")
        form.symbols.data = session.get("symbols", None)
    elif request.method == "POST":
        length = int(check_generator(request.form, "length", "12"))
        uppercase = (string.ascii_uppercase
            if check_generator(request.form, "uppercase", "y") else "")
        lowercase = (string.ascii_lowercase
            if check_generator(request.form, "lowercase", "y") else "")
        digits = string.digits if check_generator(request.form, "digits", "y") else ""
        symbols = "!@#$%^&*" if check_generator(request.form, "symbols", None) else ""
        alphabet = uppercase + lowercase + digits + symbols
        try:
            while True:
                password = "".join([secrets.choice(alphabet) for _ in range(length)])
                if (check_password(password, uppercase, lowercase, digits, symbols)):
                    break
            return password
        except IndexError:
            return ""
    return render_template("generator.html", title="Password Generator", form=form)


@entries.route("/tools/export", methods=["GET", "POST"])
@login_required
def export():
    form = ExportForm()
    if form.validate_on_submit():
        if bcrypt.check_password_hash(current_user.password, form.password.data):
            session["download"] = "csv" if form.file_format.data == "csv" else "json"
            session.pop("csrf_token", None)
            return render_template("export.html", form=form, show_modal=True)
        else:
            flash("Master Password is incorrect.", "danger")
    return render_template("export.html", title="Export Tresor", form=form)


@entries.route("/download", methods=["GET", "POST"])
@login_required
def download():
    records = Entry.query.filter_by(owner=current_user)
    filename = f"passtresor-export-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"
    try:
        return to_csv(records, filename) if (session.pop("download") == "csv") else to_json(records, filename)
    except KeyError:
        return redirect(url_for("entries.export"))

main/routes.py
from flask import Blueprint, request, render_template, redirect, url_for
from flask_login import current_user
from app.models import Entry
from app.entries.utils import decrypt


main = Blueprint("main", __name__)


@main.route("/")
@main.route("/index")
def index():
    if current_user.is_authenticated:
        search = request.args.get("q", "", type=str)
        page = request.args.get("p", 1, type=int)
        entries = (
                Entry.query.filter_by(owner=current_user)
                .filter(Entry.name.contains(search))
                .order_by(Entry.name.asc())
                .paginate(page=page, per_page=10)
                )
        context = "Entry" if entries.total == 1 else "Entries"
        return render_template("index.html", entries=entries, context=context,
                                search=search, decrypt=decrypt)
    return redirect(url_for("users.signin"))

strength/routes.py
from flask import Flask, Blueprint, render_template, request
from app.strength.pass_check import *

strength = Blueprint("strength", __name__)

@strength.route("/")
def display():
    return render_template('strength.html')


@strength.route("/tools/check_strength", methods=['GET','POST'])
def check_strength(sum=""):
    if request.method == 'POST':
        password = request.form['pwd']
        x.append(password)
        ip = vectorizer.fit_transform(x)
        switcher = {
            0: "Weak password!!!",
            1: "Moderate password!!!",
            2: "Strong password!!!",
        }
        ans = m.predict(ip)
        return render_template('strength.html', sum=switcher.get(ans[-1], " "))

    else:
        return render_template('strength.html', sum=" ")

users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, session
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from app.models import User
from app.users.forms import (
                            ChangeEmailForm,
                            DeleteAccountForm,
                            SignupForm,
                            SigninForm,
                            ChangeNameForm,
                            ChangePasswordForm,
                            )


users = Blueprint("users", __name__)


@users.route("/signup", methods=["GET", "POST"])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = SignupForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(email=form.email.data, name=form.name.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash("Account has been successfully created.", "success")
        return redirect(url_for("users.signin"))
    return render_template("signup.html", title="Sign Up", form=form)


@users.route("/signin", methods=["GET", "POST"])
def signin():
    session.permanent = True
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = SigninForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for("main.index"))
        else:
            flash("Email Address or Master Password is incorrect.", "danger")
    return render_template("signin.html", title="Sign In", form=form)


@users.route("/signout")
def signout():
    logout_user()
    return redirect(url_for("users.signin"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    name_form = ChangeNameForm()
    if name_form.name_submit.data and name_form.validate():
        current_user.name = name_form.name.data
        db.session.commit()
        flash("Name has been successfully changed.", "success")
        return redirect(url_for("users.account"))
    email_form = ChangeEmailForm()
    if email_form.email_submit.data and email_form.validate():
        if bcrypt.check_password_hash(current_user.password, email_form.password.data):
            current_user.email = email_form.email.data
            db.session.commit()
            flash("Email has been successfully changed.", "success")
            return redirect(url_for("users.account"))
        else:
            flash("Master Password is incorrect.", "danger")
    password_form = ChangePasswordForm()
    if password_form.password_submit.data and password_form.validate():
        if bcrypt.check_password_hash(
            current_user.password, password_form.old_password.data
        ):
            current_user.password = bcrypt.generate_password_hash(
                password_form.new_password.data
            ).decode("utf-8")
            db.session.commit()
            flash("Master Password has been successfully changed.", "success")
            return redirect(url_for("users.account"))
        else:
            flash("Master Password is incorrect.", "danger")
    delete_form = DeleteAccountForm()
    if delete_form.delete_submit.data and delete_form.validate():
        if bcrypt.check_password_hash(current_user.password, delete_form.password.data):
            db.session.delete(current_user)
            db.session.commit()
            flash("Account has been successfully deleted.", "success")
            return redirect(url_for("users.signin"))
        else:
            flash("Master Password is incorrect.", "danger")
    return render_template(
                        "account.html",
                        title="My Account",
                        name_form=name_form,
                        email_form=email_form,
                        password_form=password_form,
                        delete_form=delete_form,
                        )

templates/export.html
{% extends 'layout.html' %}
{% block content %}
    <section class="container bg-light my-3">
        <h5 class="export-text">Export Vault</h5>
        <form class="form-export my-3 py-3 bg-white" method="POST" novalidate>
            {{ form.hidden_tag() }}
            <fieldset class="form-group border-bottom mb-3">
                <div class="form-group mb-3">
                    {{ form.file_format.label(class="form-label") }}
                    {{ form.file_format(class="form-select") }}
                </div>
                <div class="form-group mb-3">
                    {{ form.password.label(class="form-label") }}
                    {% if form.password.errors %}
                        <div class="d-flex align-items-center">
                            {{ form.password(class="form-control is-invalid", type="password", id="password") }}
                            <i class="bi bi-eye text-primary" onclick="toggleVisibility('#password', '#toggleVisibility', 0)" id="toggleVisibility" title="Toggle Visibility"></i>
                        </div>
                        <div class="d-block invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div class="d-flex align-items-center">
                            {{ form.password(class="form-control", type="password", id="password") }}
                            <i class="bi bi-eye text-primary" onclick="toggleVisibility('#password', '#toggleVisibility', 0)" id="toggleVisibility" title="Toggle Visibility"></i>
                        </div>
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group mt-3">
                <button class="name w-100 btn" type="submit">Export</button>
            </div>
        </form>

        <!-- Modal -->
        <div class="modal fade" id="exportTresor" tabindex="-1" aria-labelledby="exportTresorLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <fieldset class="border-bottom">
                        <div class="modal-header text-danger">
                            <h5 class="modal-title" id="exportTresorLabel">
                                <i class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2"></i>
                                Export Vault
                            </h5>
                        </div>
                        <div class="modal-body">
                            This export contains your tresor data in an unencrypted format. 
                            You should not store or send the exported file over unsecure channels (such as email). 
                            Delete it immediately after you are done using it.
                        </div>
                    </fieldset>
                    <div class="d-flex justify-content-between align-items-center p-3">
                        <a class="w-50 btn btn-danger me-2" id="hideModal" href="{{ url_for('entries.download') }}">Export</a>
                        <button class="w-50 btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Show Modal -->
    {% if show_modal %}
        <script>
            $(document).ready(function() {
                $("#exportTresor").modal("show");
            });
        </script>
    {% endif %}

    <!-- Hide Modal -->
    <script>
        $(document).ready(function() {
            $("#hideModal").click(function() {
                $("#exportTresor").modal("hide");
            });
        });
    </script>
{% endblock content %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- jQuery CDN -->
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        
        <!-- Bootstrap Icons -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">  
        
        <!-- Custom CSS -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='strength_style.css') }}">


        <link rel="icon" type="image/logo" href="{{ url_for('static', filename='images/logo.png') }}">

        {% if title %}
        <title>{{ title }} | P-vault</title>
        {% else %}
        <title>P-vault</title>
        {% endif %}
    </head>

    <body class="bg-light">
        {% if current_user.is_authenticated %}
            <header class="mb-3 border-bottom">
                <div class="container-fluid">
                    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-between">
                        <div class="app-brand-user">
                            <img src="{{ url_for('static', filename='images/logo2.png') }}" class="logo">
                        </div>

                        <div class="col-12 d-flex align-items-center justify-content-center col-lg-auto mb-2 mb-lg-0">
                            <ul class="nav nav-pills nav-fill">
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('main.index') }}">
                                        <i class="bi bi-house-door"></i>
                                        Vault
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('entries.add') }}">
                                        <i class="bi bi-file-earmark-plus"></i>
                                        Add Entry
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <div class="dropdown-tools">
                                        <a href="" class="nav-link" id="dropdownTools" data-bs-toggle="dropdown" aria-expanded="false" data-bs-offset="-15, 5">
                                            <i class="bi bi-tools"></i>
                                            Tools
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu-end shadow py-1" aria-labelledby="dropdownTools">
                                            <li>
                                                <a class="dropdown-item" href="{{ url_for('entries.generator') }}">
                                                    <i class="bi bi-key me-1"></i>
                                                    Password Generator
                                                </a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item" href="{{ url_for('strength.check_strength') }}">
                                                    <i class="bi bi-shield-lock me-1"></i>
                                                    Password Strength Checker
                                                </a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item" href="{{ url_for('entries.export') }}">
                                                    <i class="bi bi-download me-1"></i>
                                                    Export Vault
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </li>
                            </ul>
                        </div>

                        <form class="form-search col-12 d-flex col-lg-auto mb-2 mb-lg-0" method="GET" action="{{ url_for('main.index', q=search) }}">
                            <input class="form-control me-2" name="q" value="{{ search }}" type="search" placeholder="Search..." aria-label="Search">
                            <div class="flex-shrink-0 dropdown-navbar">
                                <a href="" class="d-block" title="{{ current_user }}" id="dropdownUser" data-bs-toggle="dropdown" aria-expanded="false" data-bs-offset="0, 10">
                                    <img class="profile-img rounded-circle" src="{{ url_for('static', filename='images/user_logo2.png') }}" alt="profile-img" width="36" height="36">
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end mx-0 shadow py-0" aria-labelledby="dropdownUser">
                                    <li class="dropdown-text px-3 py-1">
                                        <p class="profile-name  my-0">{{ current_user.name }}</p>
                                        <small class="profile-email my-0">{{ current_user.email }}</small>
                                    </li>
                                    <li>
                                        <hr class="dropdown-divider my-1">
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{{ url_for('users.account') }}">
                                            <i class="bi bi-person me-1"></i>
                                            Account
                                        </a>
                                    </li>
                                    <li>
                                        <hr class="dropdown-divider my-1">
                                    </li>
                                    <li class="px-3 py-2">
                                        <a class="sign-out btn d-flex justify-content-center align-items-center mb-1" href="{{ url_for('users.signout') }}">
                                            <i class="bi bi-box-arrow-right me-2"></i>
                                            Sign Out
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </form>
                    </div>
                </div>
            </header>
        {% else %}
            <header>
                <div class="app-brand-nouser">
                    <img src="{{ url_for('static', filename='images/logo.png') }}" class="logo2">
                </div>
            </header>
        {% endif %}

        <main>
            <div class="mx-2 my-2">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissible d-flex align-items-center my-2 mx-2" id="alert" role="alert">
                                {% if category == 'success' %}
                                    <i class="bi bi-check-circle-fill alert-icon flex-shrink-0 me-3"></i>
                                {% elif category == 'danger' %}
                                    <i class="bi bi-exclamation-triangle-fill alert-icon flex-shrink-0 me-3"></i>
                                {% endif %}
                                <div class="alert-message">
                                    {{ message | safe }}
                                </div>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                
                {% block errors %}{% endblock errors %}

                {% block content %}{% endblock content %}
            
               <!-- <div class="bottom-text my-3">
                    <small class="text-muted">
                        © 2024 P-vault Inc.
                    </small>
                </div>-->
            </div>
        </main>

        <!-- Hide Alert After 5s -->
        <script>
            const alertEvent = document.getElementById("alert");

            if (alertEvent) {
                setTimeout(function() {
                    alertEvent.id = "alert-hide";
                }, 5000);
            }
        </script>

        <!-- Back-to-Top Button -->
        <button onclick="topFunction()" id="topBtn" title="Back to Top">
            <i class="bi bi-arrow-up-circle top-icon"></i>
        </button>

        <!-- Back-to-Top Script -->
        <script>
            var button = document.getElementById("topBtn");
            
            window.onscroll = function() {scrollFunction()};
            
            function scrollFunction() {
                if (document.body.scrollTop > 250 || document.documentElement.scrollTop > 250) {
                    button.style.display = "block";
                } else {
                    button.style.display = "none";
                }
            }
            
            function topFunction() {
                document.body.scrollTop = 0;
                document.documentElement.scrollTop = 0;
            }
        </script>

        <!-- Generate Password -->
        <script>
            $(document).ready(function() {
                $("#generatePassword").click(function() {
                    $.ajax({
                        type: "POST",
                        url: "{{ url_for('entries.generator') }}",
                        data: $(".form-generator").serializeArray(),
                        success: function (response) {
                            $("#password").val(response);
                        },
                    });
                });
            });
        </script>

        <!-- Copy to Clipboard -->
        <script>
            function copyToClipboard(element) {
                var textCopy = document.getElementById(element).value;
                navigator.clipboard.writeText(textCopy);
            }
        </script>

        <!-- Launch URL -->
        <script>
            function launchURL() {
                var url = document.getElementById("url").value;
                if (url.startsWith("http://") || url.startsWith("https://")) {
                    window.open(url).focus();
                }
            }
        </script>

        <!-- Show/Hide Password -->
        <script>
            function toggleVisibility(password, icon, index) {
                var array = document.querySelectorAll(password);
                array.forEach((element) => {
                    var type = element.getAttribute("type") === "password" ? "text" : "password";
                    element.setAttribute("type", type);
                });
                array[index].focus();
                for (const value of document.querySelectorAll(icon)) {
                    value.classList.toggle("bi-eye");
                    value.classList.toggle("bi-eye-slash");
                }
            }
        </script>

        <!-- Optional JavaScript; Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    </body>
</html>

templates/signin.html
{% extends "layout.html" %}
{% block content %}
    <section class="container">   
        <img src="{{ url_for('static', filename='images/wave.png') }}" class="wave">
        <h5 class="signin-text">Sign in or create a new account to access your secure tresor</h5>
        
        <form class="form-signin my-3 py-3 bg-white" method="POST" novalidate> 
            {{ form.hidden_tag() }}
            <fieldset class="form-group border-bottom mb-3">
                <div class="form-group mb-3">
                    {{ form.email.label(class="form-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <div class="d-block invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group mb-3">
                    {{ form.password.label(class="form-label") }}
                    {% if form.password.errors %}
                        <div class="d-flex align-items-center">
                            {{ form.password(class="form-control is-invalid", type="password", id="password") }}
                            <i class="bi bi-eye text-primary" onclick="toggleVisibility('#password', '#toggleVisibility', 0)" id="toggleVisibility" title="Toggle Visibility"></i>
                        </div>
                        <div class="d-block invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div class="d-flex align-items-center">
                            {{ form.password(class="form-control", type="password", id="password") }}
                            <i class="bi bi-eye text-primary" onclick="toggleVisibility('#password', '#toggleVisibility', 0)" id="toggleVisibility" title="Toggle Visibility"></i>
                        </div>
                    {% endif %}
                </div>
                <div class="form-group mb-3">
                    {{ form.remember(class="form-check-input", type="checkbox") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group d-flex justify-content-between align-items-center mt-3">
                <button class="name w-50 btn me-2" type="submit">
                    <i class="bi bi-box-arrow-in-right me-1"></i>
                    Sign In
                </button>
                <a class="cancel w-50 btn" href="{{ url_for('users.signup') }}">
                    <i class="bi bi-person-plus me-1"></i>
                    Sign Up
                </a>
            </div>
        </form>
    </section>
{% endblock content %}